// Code generated by go-swagger; DO NOT EDIT.

package products

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPutProductParams creates a new PutProductParams object
// with the default values initialized.
func NewPutProductParams() *PutProductParams {

	return &PutProductParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPutProductParamsWithTimeout creates a new PutProductParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPutProductParamsWithTimeout(timeout time.Duration) *PutProductParams {

	return &PutProductParams{

		timeout: timeout,
	}
}

// NewPutProductParamsWithContext creates a new PutProductParams object
// with the default values initialized, and the ability to set a context for a request
func NewPutProductParamsWithContext(ctx context.Context) *PutProductParams {

	return &PutProductParams{

		Context: ctx,
	}
}

// NewPutProductParamsWithHTTPClient creates a new PutProductParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPutProductParamsWithHTTPClient(client *http.Client) *PutProductParams {

	return &PutProductParams{
		HTTPClient: client,
	}
}

/*PutProductParams contains all the parameters to send to the API endpoint
for the put product operation typically these are written to a http.Request
*/
type PutProductParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the put product params
func (o *PutProductParams) WithTimeout(timeout time.Duration) *PutProductParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put product params
func (o *PutProductParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put product params
func (o *PutProductParams) WithContext(ctx context.Context) *PutProductParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put product params
func (o *PutProductParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put product params
func (o *PutProductParams) WithHTTPClient(client *http.Client) *PutProductParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put product params
func (o *PutProductParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PutProductParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
